# Image file type to be used in augmentation operations
type: 'png'

# Target number of images per category
goal: 400

# Number of fold directories (k-folds) in the dataset
k_folds: 10

# Base directory where the image data is stored
base_dir: './BD/CPD1_Dn_VTcr_210425/'

# List of views (e.g., EQUATORIAL and POLAR) to be processed
views:
  - 'EQUATORIAL'
  - 'POLAR'

# Verbosity level for console logs (0 = silent, 1 or more = verbose)
verbose: 1
